Test
anastasiya1745/Practice pull request #5
Opened 2021-08-14 18:41 UTC by anastasiya1745

create and update Logger
convert to Maven project, add depencies and plugin

2021-08-14 19:40 UTC, anastasiya1745 reviewed
this commit is incorrect

2021-08-14 20:24 UTC, apollyonix requested changes

2021-08-14 20:24 UTC, apollyonix commented on .gitignore
> +*pom.xml
pom.xml нельзя игнорировать. он должен быть в репозитории, чтобы его можно было вытащить вместе со всеми исходниками, и на основании его - подтянуть все зависимости, которые в pom.xml собственно и описаны

2021-08-15 07:21 UTC, apollyonix approved these changes

2021-08-15 07:21 UTC, merged